export const EVENTS = {
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_CONFIRMED: "ORDER_CONFIRMED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  ORDER_STATUS_CHANGED: "ORDER_STATUS_CHANGED",
  ORDER_DELIVERED: "ORDER_DELIVERED",

  INVENTORY_RESERVED: "INVENTORY_RESERVED",
  INVENTORY_COMMITTED: "INVENTORY_COMMITTED",
  INVENTORY_RELEASED: "INVENTORY_RELEASED",
  INVENTORY_LOW: "INVENTORY_LOW",

  SHIPMENT_CREATED: "SHIPMENT_CREATED",
  SHIPMENT_STATUS_CHANGED: "SHIPMENT_STATUS_CHANGED",
} as const;

export type EventName = (typeof EVENTS)[keyof typeof EVENTS];